[local]
localhost

[mongodb]
mongodb.deep90s.online

[redis]
redis.deep90s.online

[mysql]
mysql.deep90s.online

[rabbitmq]
rabbitmq.deep90s.online

[catalogue]
catalogue.deep90s.online

[user]
user.deep90s.online

[cart]
cart.deep90s.online

[shipping]
shipping.deep90s.online

[payment]
payment.deep90s.online

[frontend]
frontend.deep90s.online